"""The online scorer must produce the numbers the committed predictions carry.

This is the guard against silent scoring drift. The refactor that extracted the
feature mapping, and the switch from the `shap` package to the booster's own
`pred_contribs`, both changed how the numbers are produced without being
supposed to change the numbers. Nothing else in the suite would have noticed if
they had: a wrong score is still a float between 0 and 1, and the dashboard
would have rendered it without complaint.

`golden_vectors.json` is regenerated by
`cd backend && python -m ml.generate_predictions --dump-vectors` and must be
regenerated whenever the model changes.
"""

from __future__ import annotations

import json
import pathlib

import pytest

from inference.scorer import FeatureOrderMismatch, Scorer

GOLDEN = json.loads((pathlib.Path(__file__).parent / "golden_vectors.json").read_text())
MODEL_PATH = pathlib.Path(__file__).parents[2] / "ml" / "model.joblib"

TOLERANCE = 1e-6


@pytest.fixture(scope="module")
def scorer() -> Scorer:
    return Scorer(model_path=MODEL_PATH)


def test_feature_names_come_from_the_booster(scorer: Scorer):
    assert scorer.feature_names == GOLDEN["feature_names"]
    assert len(scorer.feature_names) == 7
    # The documented sensor list that no model consumes must not have crept in.
    for absent in ("vibration", "door", "current"):
        assert not any(absent in name.lower() for name in scorer.feature_names)


def test_scores_reproduce_the_committed_predictions(scorer: Scorer):
    scores, _ = scorer.score(GOLDEN["feature_names"], GOLDEN["rows"])

    assert len(scores) == len(GOLDEN["expected_scores"])
    worst = max(
        abs(actual - expected)
        for actual, expected in zip(scores, GOLDEN["expected_scores"], strict=True)
    )
    assert worst < TOLERANCE, f"max score drift {worst} exceeds {TOLERANCE}"


def test_contribution_impacts_normalise_to_one(scorer: Scorer):
    """Top-3 normalised impacts must sum to 1.0, as the offline script asserts."""
    _, contributions = scorer.score(GOLDEN["feature_names"], GOLDEN["rows"])

    for row in contributions:
        top3 = sorted((abs(c) for c in row), reverse=True)[:3]
        impacts = [c / sum(top3) for c in top3]
        assert 0.99 <= sum(impacts) <= 1.01


def test_contributions_have_one_column_per_feature(scorer: Scorer):
    """The bias column pred_contribs appends must be dropped, not passed on."""
    _, contributions = scorer.score(GOLDEN["feature_names"], GOLDEN["rows"])

    assert all(len(row) == len(scorer.feature_names) for row in contributions)


def test_a_reordered_column_list_is_rejected(scorer: Scorer):
    reordered = list(reversed(GOLDEN["feature_names"]))

    with pytest.raises(FeatureOrderMismatch):
        scorer.score(reordered, GOLDEN["rows"])


def test_a_row_of_the_wrong_width_is_rejected(scorer: Scorer):
    with pytest.raises(FeatureOrderMismatch):
        scorer.score(GOLDEN["feature_names"], [[1.0, 2.0]])


def test_celsius_instead_of_kelvin_corrupts_scores_without_collapsing_them():
    """Measured, because the plan's assumption about this was wrong.

    The expectation going in was that Celsius input would send every tree down
    the same branch and hand the whole fleet one identical score — which would
    make "fleet score variance > 0" a sufficient canary. It does not. The other
    five features still discriminate, so the fleet comes back with 51 distinct
    scores and a standard deviation within 0.002 of the correct one, while 10
    of 70 elevators land in the wrong risk band and one moves by 0.996.

    That is worse than the collapse, not better: the corrupted output passes
    every distributional smell test. This is why the guard is a range assertion
    on the temperature columns at the conversion boundary, and not a variance
    check on the output.
    """
    scorer = Scorer(model_path=MODEL_PATH)

    def band(score: float) -> str:
        return "high" if score > 0.80 else ("medium" if score >= 0.50 else "low")

    kelvin_scores, _ = scorer.score(GOLDEN["feature_names"], GOLDEN["rows"])

    celsius_rows = [list(row) for row in GOLDEN["rows"]]
    for row in celsius_rows:
        row[0] -= 273.15  # Air_temperature__K
        row[1] -= 273.15  # Process_temperature__K
    celsius_scores, _ = scorer.score(GOLDEN["feature_names"], celsius_rows)

    # The corruption is real: most scores move, and some move bands.
    moved = sum(1 for k, c in zip(kelvin_scores, celsius_scores, strict=True) if abs(k - c) > 1e-6)
    reband = sum(
        1 for k, c in zip(kelvin_scores, celsius_scores, strict=True) if band(k) != band(c)
    )
    assert moved > len(kelvin_scores) // 2, "Celsius input must materially change scores"
    assert reband > 0, "Celsius input must move at least one elevator into the wrong band"

    # And it is invisible to a variance check, which is the point.
    assert len(set(round(s, 6) for s in celsius_scores)) > 1, (
        "a variance canary would not catch this — do not reintroduce one as the guard"
    )
