"""add elevators last_scored_at

Revision ID: 3d92a2ed3fb5
Revises: 4be52fe3ba9b
Create Date: 2026-08-30 10:54:49.609926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d92a2ed3fb5'
down_revision: Union[str, None] = '4be52fe3ba9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elevators', sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elevators', 'last_scored_at')
    # ### end Alembic commands ###
