"""create telemetry_readings

Revision ID: 4be52fe3ba9b
Revises: aa3f0fc81e9c
Create Date: 2026-08-30 10:30:02.807493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be52fe3ba9b'
down_revision: Union[str, None] = 'aa3f0fc81e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ambient_temperature_c', sa.Float(), nullable=False),
    sa.Column('motor_temperature_c', sa.Float(), nullable=False),
    sa.Column('motor_speed_rpm', sa.Float(), nullable=False),
    sa.Column('load_torque_nm', sa.Float(), nullable=False),
    sa.Column('motor_run_hours_cumulative', sa.Float(), nullable=True),
    sa.Column('vibration_mm_s', sa.Float(), nullable=True),
    sa.Column('door_cycles', sa.Integer(), nullable=True),
    sa.Column('door_errors', sa.Integer(), nullable=True),
    sa.Column('motor_current_a', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Hand-written: the DESC ordering is expressed with sa.text() rather than
    # through postgresql_ops, which is the operator-class slot and not the sort
    # order. Both indexes exist for a scan direction, so the ordering is the
    # point of them.
    #
    # Deferred deliberately: at the change-3 ingest cadence (15 min x 100
    # elevators ~ 9,600 rows/day) partitioning and a BRIN index on recorded_at
    # are premature. Revisit above roughly 50M rows. Bounded growth is handled
    # by the retention prune at the end of each inference run, not by the
    # physical layout.
    op.create_index(
        'ix_telemetry_readings_elevator_recorded',
        'telemetry_readings',
        ['elevator_id', sa.text('recorded_at DESC')],
        unique=False,
    )
    op.create_index(
        'ix_telemetry_readings_recorded',
        'telemetry_readings',
        [sa.text('recorded_at DESC')],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_readings_recorded', table_name='telemetry_readings')
    op.drop_index('ix_telemetry_readings_elevator_recorded', table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    # ### end Alembic commands ###
