"""create elevators, features, trend points, visit reports

Revision ID: 638e311fa8e1
Revises: 
Create Date: 2026-06-11 16:22:28.712147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '638e311fa8e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elevators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('building_name', sa.String(), nullable=False),
    sa.Column('building_type', sa.String(), nullable=False),
    sa.Column('floor_count', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('age_years', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('last_visit_date', sa.String(), nullable=False),
    sa.Column('last_visit_technician', sa.String(), nullable=False),
    sa.Column('last_visit_notes', sa.String(), nullable=False),
    sa.Column('nl_explanation', sa.String(), nullable=False),
    sa.Column('in_model_scope', sa.Boolean(), nullable=False),
    sa.Column('hourly_trips_avg', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elevator_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elevator_trend_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elevator_id', 'day_index')
    )
    op.create_table('visit_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(), nullable=False),
    sa.Column('technician_name', sa.String(), nullable=False),
    sa.Column('visit_date', sa.String(), nullable=False),
    sa.Column('failure_found', sa.Boolean(), nullable=False),
    sa.Column('components_replaced', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('parameters_corrected', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_reports')
    op.drop_table('elevator_trend_points')
    op.drop_table('elevator_features')
    op.drop_table('elevators')
    # ### end Alembic commands ###
