#!/bin/sh
# Reload nginx after a certificate has been renewed.
#
# Installed to /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh by
# install-renewal.sh. Certbot runs every executable in that directory after a
# *successful* renewal, whoever invoked certbot — the timer, an operator typing
# `certbot renew`, or a mechanism that does not exist yet. That is why it lives
# there instead of behind a --deploy-hook flag: the reload cannot be lost by the
# person doing the renewing, which is exactly what happened while recovering from
# the 2026-09-10 expiry.
#
# Do not edit this file on the instance. Every deploy overwrites it from the
# repository — see deploy/tls/README.md.
set -eu

# `exec -T` is load-bearing. `docker compose exec` allocates a controlling
# terminal by default and fails when there is none, and there is none in a
# systemd timer any more than there was in cron. Without it a renewal lands on
# disk while nginx goes on presenting the expired certificate it holds in memory:
# the same outage, wearing the clothes of a success.
#
# `cd` followed by a relative -f mirrors .github/workflows/deploy.yml exactly, so
# both derive the same Compose project name and `exec` cannot fail to find the
# container because the two disagreed about what the project is called.
cd /opt/elevator
exec docker compose -f docker-compose.prod.yml exec -T nginx nginx -s reload
